version: '3'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:11.0.3
    ports:
      - "8180:8080"
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
  app:
    image: sagov/quarkus:latest
    ports:
      - "8080:8080"
    environment:
      MP_JWT_VERIFY_PUBLICKEY_LOCATION: http://keycloak:8080/auth/realms/quarkus/protocol/openid-connect/certs
