apiVersion: batch/v1
kind: Job
metadata:
  name: liquibase
  labels:
    app: quarkus-app
spec:
  template:
    spec:
      containers:
        - name: liquibase
          image: docker.io/liquibase/liquibase:4.23.1-alpine
          args:
            [
              "--url=jdbc:postgresql://postgresql:5432/quarkusdb1",
              "--username=quarkus",
              "--password=password",
              "--defaultsFile=/liquibase/changelog/liquibase.properties",
              "--changeLogFile=db.changelog-master.xml",
              "--logLevel=info",
              "update"
            ]
          volumeMounts:
            - name: liquibase
              mountPath: "/liquibase/changelog"
      volumes:
        - name: liquibase
          configMap:
            name: liquibase
      restartPolicy: Never
  backoffLimit: 0
