apiVersion: v1
kind: ConfigMap
metadata:
  name: quarkus
  labels:
    app: quarkus-app
data:
  QUARKUS_LOG_CONSOLE_JSON: "false"
  QUARKUS_DATASOURCE_USERNAME: quarkus
  QUARKUS_DATASOURCE_PASSWORD: password
  QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgresql:5432/quarkusdb
  MP_JWT_VERIFY_PUBLICKEY_LOCATION: https://keycloak:8080/realms/quarkus/protocol/openid-connect/certs
  MP_JWT_VERIFY_ISSUER: https://keycloak:8080/realms/quarkus
