apiVersion: apps/v1
kind: Deployment
metadata:
  name: quarkus
  labels:
    app: quarkus-app
spec:
  replicas: 0
  selector:
    matchLabels:
      app: quarkus-app
  template:
    metadata:
      labels:
        app: quarkus-app
    spec:
      containers:
        - name: app
          image: ghcr.io/juliaaano/quarkus:latest
          env:
            - name: MY_SAMPLE_ENV
              value: mySampleEnv
          envFrom:
            - configMapRef:
                name: quarkus
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: sample-volume
              mountPath: /app/sample-volume
          readinessProbe:
            httpGet:
              path: /q/health/ready
              port: 8080
              scheme: HTTP
          livenessProbe:
            httpGet:
              path: /q/health/live
              port: 8080
              scheme: HTTP
          resources:
            requests:
              cpu: "250m"
              memory: 512Mi
            limits:
              cpu: "500m"
              memory: 1Gi
      volumes:
        - name: sample-volume
          emptyDir: {}
