name: scanning

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    paths:
      - "src/**"
      - "pom.xml"
  schedule:
    - cron: "30 1 * * *"

jobs:
  codeql:
    runs-on: ubuntu-latest
    steps:
      - name: jdk11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
      - name: codeql init
        uses: github/codeql-action/init@v1
        with:
          languages: java
      - name: checkout
        uses: actions/checkout@v2
      - name: cache ~/.m2
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: mvn compile
        run: mvn --show-version --batch-mode compile
      - name: codeql analyze
        uses: github/codeql-action/analyze@v1
